### ISSUE TITLE
chapter mixing babelnovel.com 

### ISSUE THREAD

**Issue by uisufian** [dipu-bd/lightnovel-crawler#156]
**on babelnovel.com one chapter content getting mixing with other chapter **
like first pragraph is from chapter 2280 and next prgraph from a random chapeter . .

**Let us know**
- Novel URL: [e.g. https://babelnovel.com/books/nine-star-hegemon-body-arts
- App Version: [e.g. 2.9.13]
- Package: [exe , and pipe both ]
- OS: [e.g. Windows 10
![Capture](https://user-images.githubusercontent.com/24265976/59972092-b24ed300-95aa-11e9-98f8-fbbb04b1a110.PNG)
]

**Comment by dipu-bd** [comment]
It is already fixed, but not yet released

**Comment by uisufian** [comment]
its would be great if could update the pypi file.

Thanks bro .

**Comment by dipu-bd** [comment]
released the new version.  you can get it from pypi now.

```
pip install -U lightnovel-crawler
```

**Comment by Flwk** [comment]
Hello

I have download the new version (exe) and i still have the same problem as here

Is it normal ?

**Comment by uisufian** [comment]
> 
> 
> Hello
> 
> I have download the new version (exe) and i still have the same problem as here
> 
> Is it normal ?

exe file not update it yet.. look at version its v2.9.13 .. updated version is : 2.10.0  .. which only add on https://pypi.org/

**Comment by dipu-bd** [comment]
updated the exe file
